zbxmail:
        image: 'zoubixmail:latest'
        restart: unless-stopped
        container_name : 'zoubixmail'
        hostname: 'mail.zoubix.net'
#        environment:
        volumes:
                - '/fsdocker/zoubixmail/var-spool-postfix:/var/spool/postfix'
                - '/fsdocker/zoubixmail/home:/home'
                - '/fsdocker/zoubixmail/var/lib/rspamd:/var/lib/rspamd'
        ports:
                - "IP_INTERNE:25:25"
                - "IP_INTERNE:993:993"
                - "IP_INTERNE:11334:11334"
#
